name: CI with NIX

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT used by GCP auth step
      contents: read  # This is required for actions/checkout

    steps:
    - uses: actions/checkout@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1.1.1
      with:
        workload_identity_provider: projects/1000420590118/locations/global/workloadIdentityPools/github-workflows/providers/github-workflows
        service_account: github-workflows@dvf-deversifi-dev.iam.gserviceaccount.com

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command

    - id: secrets
      uses: google-github-actions/get-secretmanager-secrets@v1.0.1
      with:
        secrets: github_token:dvf-shared/GITHUB_TOKEN_ALL_REPOS_READ

    - name: Bootstrap nix config
      env:
        GITHUB_TOKEN: '${{ steps.secrets.outputs.github_token }}'
      run: ./nix/netrc-create.sh

    - name: Run pr-step
      run: nix run --impure -f nix/pkgs.nix ci.pr-step

    - name: Run deploy-step
      run: |
        if [[ ${{ github.ref }} == refs/heads/master ]]
        then
          # NOTE: if this fails with a 403 it's most likely due to not bumping
          #   version in package.json
          nix run --impure -f nix/pkgs.nix ci.deploy-step
        else
          echo skipping
        fi
